### ISSUE TITLE
Crash on Manga Download Request

### ISSUE THREAD

**Issue by Lord-Haji** [AnimeshShaw/MangaScrapper#2]
![scrnsht](https://i.imgur.com/0sl08yP.png)

**Comment by AnimeshShaw** [comment]
Have you run the following first:

```pip install -r requirements.txt```

It will install all the required python modules.

**Comment by Lord-Haji** [comment]
Yes, I checked my previous console log carefully actually installing one of
it's components required root so the requirements install failed. I fixed
it later tho.

Thanks!
